/**
 * File contains: 
 * 
 * Types and Interface implementations that cover usage
 * of the data layer <==> display layer
 * 
 * Note: since this is generated by hand, if the auto generated
 * types change ( db change ) then the new types need to be moved 
 * here if they belong to the auction models
 * 
 */

/** from supabase.ts */
export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json }
    | Json[]

/** from supabase.ts */
export type T_AuctionRowModel = {
    allowed_free_bids: string[] | null
    auction_id: string
    bid_currency: string | null
    charity_id: string
    created_at: string | null
    description: string
    high_bid_value: number | null
    increment: number
    item_id: string | null
    minimum_bids: number | null
    name: string
    opening_bid_value: number
    over_bid_good_time_active: boolean | null
    over_bid_good_time_early_fee: number | null
    over_bid_good_time_late_fee: number | null
    over_bid_good_time_often_fee: number | null
    over_bid_good_time_threshold_field: Json | null
    status: string
    top_bid_duration: number | null
    type: string
}

export interface I_AuctionRowModel {
    auction: T_AuctionRowModel
}

export interface I_AuctionRowCollection {
    auctions: T_AuctionRowModel[] | []
}

/*
export interface I_UseAuctionsQueryReturn {
    queryStatus: {
        isLoading: boolean,
        isError: boolean
    },
    auctions: I_AuctionRowModel[] | null,
    hasError: boolean,
    errorMessage: string,
    errorObj: any
}
*/